services:
  postgres:
    image: postgres:latest
    container_name: library
    environment:
      POSTGRES_DB: library
      POSTGRES_USER: library
      POSTGRES_PASSWORD: library
    ports:
      - "5435:5432"